package br.com.furb.dss.view;

import br.com.furb.dss.controller.ListaComprasDao;
import br.com.furb.dss.controller.UsuarioController;
import br.com.furb.dss.controller.UsuarioDao;
import br.com.furb.dss.model.Roles;
import br.com.furb.dss.model.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author drmartini
 */
public class ListaCompras extends javax.swing.JFrame {

    //Logged User
    private final Usuario user;
    private final JFrame parentPanel;

    /**
     * Creates new form ListaCompras
     *
     * @param user - Current logged user
     * @param parentPanel - Parent panel to open again after the disposal of
     * this one
     */
    public ListaCompras(Usuario user, JFrame parentPanel) {
        initComponents();
        this.user = user;
        this.parentPanel = parentPanel;
        jButtonSearchUser.setVisible(user.hasRole(Roles.moderador));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNewUser = new javax.swing.JButton();
        jButtonSearchUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShopList = new javax.swing.JTextArea();
        jButtonTesteSalvar = new javax.swing.JButton();
        jButtonTesteCarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonNewUser.setText("Novo Usuário");
        jButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUserActionPerformed(evt);
            }
        });

        jButtonSearchUser.setText("Consultar Usuários");
        jButtonSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUserActionPerformed(evt);
            }
        });

        jTextAreaShopList.setColumns(20);
        jTextAreaShopList.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShopList);

        jButtonTesteSalvar.setText("Salva texto");
        jButtonTesteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTesteSalvarActionPerformed(evt);
            }
        });

        jButtonTesteCarregar.setText("Carrega texto");
        jButtonTesteCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTesteCarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonTesteSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNewUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearchUser)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTesteCarregar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonTesteCarregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewUser)
                    .addComponent(jButtonSearchUser)
                    .addComponent(jButtonTesteSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parentPanel.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUserActionPerformed
        new CadastrarUsuarios(user, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNewUserActionPerformed

    private void jButtonSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUserActionPerformed
        new ConsultarUsuarios(user, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSearchUserActionPerformed

    private void jButtonTesteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTesteSalvarActionPerformed
        ListaComprasDao lisComprasDao = ListaComprasDao.getInstance();
        Usuario usuario;
        usuario = UsuarioController.getInstance().getUsuarioLogado();
        br.com.furb.dss.model.ListaCompras lisCompras = new br.com.furb.dss.model.ListaCompras("", usuario);
        lisCompras.setLista(jTextAreaShopList.getText());
        lisComprasDao.persist(lisCompras);
                
    }//GEN-LAST:event_jButtonTesteSalvarActionPerformed

    private void jButtonTesteCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTesteCarregarActionPerformed
        ListaComprasDao lisComprasDao = ListaComprasDao.getInstance();
        try{
        br.com.furb.dss.model.ListaCompras listaCompras = lisComprasDao.getById(1);
        jTextAreaShopList.setText(listaCompras.getLista());
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButtonTesteCarregarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewUser;
    private javax.swing.JButton jButtonSearchUser;
    private javax.swing.JButton jButtonTesteCarregar;
    private javax.swing.JButton jButtonTesteSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaShopList;
    // End of variables declaration//GEN-END:variables
}
