package br.com.furb.dss.view;

import br.com.furb.dss.model.Roles;
import br.com.furb.dss.model.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author drmartini
 */
public class ListaCompras extends javax.swing.JFrame {

    //Logged User
    private final Usuario user;
    private final JFrame parentPanel;

    /**
     * Creates new form ListaCompras
     *
     * @param user - Current logged user
     * @param parentPanel - Parent panel to open again after the disposal of
     * this one
     */
    public ListaCompras(Usuario user, JFrame parentPanel) {
        initComponents();
        this.user = user;
        this.parentPanel = parentPanel;
        jButtonSearchUser.setVisible(user.hasRole(Roles.moderador));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNewUser = new javax.swing.JButton();
        jButtonSearchUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShopList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonNewUser.setText("Novo Usuário");
        jButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUserActionPerformed(evt);
            }
        });

        jButtonSearchUser.setText("Consultar Usuários");
        jButtonSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUserActionPerformed(evt);
            }
        });

        jTextAreaShopList.setColumns(20);
        jTextAreaShopList.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShopList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jButtonNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearchUser)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewUser)
                    .addComponent(jButtonSearchUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parentPanel.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUserActionPerformed
        new CadastrarUsuarios(user, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNewUserActionPerformed

    private void jButtonSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUserActionPerformed
        new ConsultarUsuarios(user, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSearchUserActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewUser;
    private javax.swing.JButton jButtonSearchUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaShopList;
    // End of variables declaration//GEN-END:variables
}
